package com.finwise.scheduler;

import com.finwise.config.RabbitMqConfig;
import com.finwise.dto.notification.NotificationEvent;
import com.finwise.dto.notification.NotificationEvent.NotificationChannel;
import com.finwise.dto.notification.NotificationEvent.NotificationType;
import com.finwise.entity.User;
import com.finwise.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.quartz.DisallowConcurrentExecution;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.scheduling.quartz.QuartzJobBean;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@Slf4j
@Component
@DisallowConcurrentExecution
@RequiredArgsConstructor
public class DailyDigestJob extends QuartzJobBean {

    private final UserRepository userRepository;
    private final RabbitTemplate rabbitTemplate;

    @Override
    protected void executeInternal(JobExecutionContext context) throws JobExecutionException {
        log.info("Executing clustered Quartz job: DailyDigestJob for date: {}", LocalDate.now());

        List<User> activeUsers = userRepository.findAll().stream()
                .filter(u -> u.getStatus() == User.UserStatus.ACTIVE && !u.isDeleted())
                .toList();

        for (User user : activeUsers) {
            NotificationEvent event = NotificationEvent.builder()
                    .eventId(UUID.randomUUID().toString())
                    .userId(user.getId())
                    .type(NotificationType.MONTHLY_DIGEST)
                    .channel(NotificationChannel.EMAIL)
                    .title("Your Daily Financial Pulse — " + LocalDate.now())
                    .message("Review your daily ledger snapshot, track active budgets, and review new insights generated by FinWise AI.")
                    .build();

            rabbitTemplate.convertAndSend(RabbitMqConfig.TOPIC_EXCHANGE, "notification.email.digest", event);
        }
    }
}
